In [1]:
from pathlib import Path
import json
import pandas as pd
from IPython.display import display, HTML

In [2]:
# Define the file path relative to project root
file_path = Path("../data/firm_explanations.json")

In [3]:
# Read the JSON file
with file_path.open('r') as file:
    firm_explanations = json.load(file)

# Remove features that start with 'Standardized_country'
for company in firm_explanations:
    firm_explanations[company]['top_features'] = [
        feature for feature in firm_explanations[company]['top_features']
        if not feature['feature'].startswith('Standardized_country')
    ]

# Print a sample to verify
print(firm_explanations)

{'MOON WEARABLES DA': {'predicted_proba': 0.3451324999332428, 'top_features': [{'feature': 'Consolidation_code_NF', 'shap_value': -0.5453734397888184, 'feature_value': True}, {'feature': 'Capital_EUR___', 'shap_value': -0.3749895989894867, 'feature_value': 0.0}, {'feature': 'Current_assets_EUR_Last_avail__yr', 'shap_value': 0.1444517970085144, 'feature_value': 362620.634501137}, {'feature': 'Current_assets_EUR___', 'shap_value': 0.1381048858165741, 'feature_value': -0.014479097142360734}]}, 'HUAWEI TECHNOLOGIES RESEARCH & DEVELOPMENT (UK) LIMITED': {'predicted_proba': 0.042746979743242264, 'top_features': [{'feature': 'Capital_EUR___', 'shap_value': -1.6214265823364258, 'feature_value': 0.01863731197531898}, {'feature': 'Tangible_fixed_assets_EUR_Last_avail__yr', 'shap_value': 1.0874478816986084, 'feature_value': 78433060.9515453}, {'feature': 'Of_which_cash_and_cash_equivalent_EUR_Last_avail__yr', 'shap_value': -0.6029041409492493, 'feature_value': 46067447.7850467}, {'feature': 'Number_of_employees_Last_avail__yr', 'shap_value': -0.576539933681488, 'feature_value': 381.0}, {'feature': 'Long_term_debt_EUR_Last_avail__yr', 'shap_value': 0.4195011258125305, 'feature_value': 12048007.3639939}]}, 'ORECON LIMITED': {'predicted_proba': 0.9442474842071533, 'top_features': [{'feature': 'Capital_EUR___', 'shap_value': 1.8140850067138672, 'feature_value': -0.167059134971811}, {'feature': 'Intangible_assets_EUR___', 'shap_value': 0.5357787609100342, 'feature_value': 0.4186485980498375}, {'feature': 'Non_current_assets_EUR___', 'shap_value': -0.4364358186721802, 'feature_value': 2.666674081825429}, {'feature': 'Number_of_employees_Last_avail__yr', 'shap_value': 0.39591726660728455, 'feature_value': 19.0}, {'feature': 'Debtors_EUR_Last_avail__yr', 'shap_value': 0.2592942714691162, 'feature_value': 0.0}]}, 'JOB4FIVER LIMITED': {'predicted_proba': 0.09434433281421661, 'top_features': [{'feature': 'P_L_before_tax_EUR___', 'shap_value': -0.5135595798492432, 'feature_value': nan}, {'feature': 'P_L_for_period___Net_income__EUR_Last_avail__yr', 'shap_value': -0.4065324068069458, 'feature_value': 864449.0}, {'feature': 'Number_of_employees_Last_avail__yr', 'shap_value': -0.354245662689209, 'feature_value': 45.0}, {'feature': 'Debtors_EUR_Last_avail__yr', 'shap_value': -0.3379736542701721, 'feature_value': 328852.84670317493}]}, 'ENORON LTD': {'predicted_proba': 0.3806627094745636, 'top_features': [{'feature': 'Capital_EUR_Last_avail__yr', 'shap_value': -1.2021156549453735, 'feature_value': 0.0}, {'feature': 'Current_liabilities_EUR_Last_avail__yr', 'shap_value': 0.4591112732887268, 'feature_value': 0.0}, {'feature': 'Total_shareholders__funds_and_liabilities_EUR___', 'shap_value': 0.4439382255077362, 'feature_value': -0.991721913753474}, {'feature': 'Current_assets_EUR_Last_avail__yr', 'shap_value': 0.3243770897388458, 'feature_value': 947.227675225927}, {'feature': 'Debtors_EUR_Last_avail__yr', 'shap_value': 0.26883018016815186, 'feature_value': 0.0}]}, 'CULL MICRO IMAGING LTD': {'predicted_proba': 0.9036389589309692, 'top_features': [{'feature': 'Capital_EUR___', 'shap_value': 1.2251278162002563, 'feature_value': 0.05823027936565642}, {'feature': 'Non_current_liabilities_EUR___', 'shap_value': -0.5083208680152893, 'feature_value': -0.7452644595372491}, {'feature': 'Solvency_ratio__Asset_based____', 'shap_value': -0.5073314309120178, 'feature_value': 1.246020366898276}, {'feature': 'Of_which_cash_and_cash_equivalent_EUR_Last_avail__yr', 'shap_value': 0.38292020559310913, 'feature_value': 11933.6344258889}, {'feature': 'Current_liabilities_EUR___', 'shap_value': -0.3093808591365814, 'feature_value': 0.1423021726199441}]}, 'AROMAPASS': {'predicted_proba': 0.4982261061668396, 'top_features': [{'feature': 'Consolidation_code_NF', 'shap_value': -0.3855734169483185, 'feature_value': True}, {'feature': 'Capital_EUR___', 'shap_value': -0.3739273250102997, 'feature_value': 0.0}, {'feature': 'Number_of_employees_Last_avail__yr', 'shap_value': 0.3446477949619293, 'feature_value': 24.0}, {'feature': 'Other_current_liabilities_EUR___', 'shap_value': -0.1848386824131012, 'feature_value': -0.05551252642535617}]}, 'AC IMMUNE SA': {'predicted_proba': 0.013071203604340553, 'top_features': [{'feature': 'Quoted_Yes', 'shap_value': -2.649095058441162, 'feature_value': True}, {'feature': 'Capital_EUR___', 'shap_value': -0.9318901896476746, 'feature_value': 0.003782304982704925}, {'feature': 'Capital_EUR_Last_avail__yr', 'shap_value': -0.4860439896583557, 'feature_value': 2348527.37949007}, {'feature': 'Number_of_employees_Last_avail__yr', 'shap_value': 0.2618298828601837, 'feature_value': 15.0}]}, 'CARE AND SHARE ASSOCIATES UNLIMITED': {'predicted_proba': 0.6747853755950928, 'top_features': [{'feature': 'Capital_EUR___', 'shap_value': 0.8877047300338745, 'feature_value': -0.03754651862041981}, {'feature': 'Capital_EUR_Last_avail__yr', 'shap_value': -0.6269041299819946, 'feature_value': 1.13797702478446}, {'feature': 'Debtors_EUR___', 'shap_value': -0.4313643276691437, 'feature_value': nan}, {'feature': 'P_L_before_tax_EUR___', 'shap_value': -0.4290207326412201, 'feature_value': nan}, {'feature': 'Consolidation_code_LF', 'shap_value': -0.3886358141899109, 'feature_value': True}]}, 'VIVA LABS AS': {'predicted_proba': 0.6709274053573608, 'top_features': [{'feature': 'Capital_EUR___', 'shap_value': 0.776790201663971, 'feature_value': 3.477935467892946}, {'feature': 'Debtors_EUR_Last_avail__yr', 'shap_value': -0.6013550162315369, 'feature_value': 241416.181997063}, {'feature': 'Tangible_fixed_assets_EUR_Last_avail__yr', 'shap_value': -0.3857573866844177, 'feature_value': 0.0}, {'feature': 'Solvency_ratio__Asset_based____', 'shap_value': 0.2930856943130493, 'feature_value': -9.751487698729905}, {'feature': 'Other_shareholders_funds_EUR___', 'shap_value': 0.29012584686279297, 'feature_value': 0.6613661234278138}]}, 'EQUIPE ZORGBEDRIJVEN NEDERLAND B.V.': {'predicted_proba': 0.24523819983005524, 'top_features': [{'feature': 'Tangible_fixed_assets_EUR___', 'shap_value': 0.39485710859298706, 'feature_value': 1.535229688397508}, {'feature': 'Debtors_EUR_Last_avail__yr', 'shap_value': -0.33897510170936584, 'feature_value': 898585.0}, {'feature': 'Number_of_employees_Last_avail__yr', 'shap_value': -0.32130420207977295, 'feature_value': 55.0}, {'feature': 'Tangible_fixed_assets_EUR_Last_avail__yr', 'shap_value': 0.3116098642349243, 'feature_value': 2581992.0}, {'feature': 'Total_assets_EUR_Last_avail__yr', 'shap_value': -0.2560257315635681, 'feature_value': 7760791.0}]}, 'LAND INSIGHT LTD': {'predicted_proba': 0.24594746530056, 'top_features': [{'feature': 'Number_of_employees_Last_avail__yr', 'shap_value': -0.7932541966438293, 'feature_value': 79.0}, {'feature': 'Capital_EUR___', 'shap_value': -0.38659268617630005, 'feature_value': 0.0}, {'feature': 'Debtors_EUR___', 'shap_value': 0.20534899830818176, 'feature_value': -0.28759991876400676}, {'feature': 'Other_current_liabilities_EUR___', 'shap_value': -0.19284451007843018, 'feature_value': -0.2347359075523564}]}, 'BLACKFORD ANALYSIS LIMITED': {'predicted_proba': 0.2986224591732025, 'top_features': [{'feature': 'Capital_EUR___', 'shap_value': 1.2553550004959106, 'feature_value': 0.140175402450005}, {'feature': 'Of_which_cash_and_cash_equivalent_EUR_Last_avail__yr', 'shap_value': -0.7941120266914368, 'feature_value': 4463584.04217435}, {'feature': 'Number_of_employees_Last_avail__yr', 'shap_value': -0.3977983593940735, 'feature_value': 86.0}, {'feature': 'Debtors_EUR_Last_avail__yr', 'shap_value': -0.2799812853336334, 'feature_value': 455470.676019715}, {'feature': 'Current_liabilities_EUR_Last_avail__yr', 'shap_value': -0.27562081813812256, 'feature_value': 11081382.5317102}]}, 'EPERI GMBH': {'predicted_proba': 0.46962589025497437, 'top_features': [{'feature': 'Shareholders_funds_EUR___', 'shap_value': 0.4560419023036957, 'feature_value': -1.098672396799023}, {'feature': 'Capital_EUR___', 'shap_value': -0.3394162654876709, 'feature_value': 0.0}, {'feature': 'Other_shareholders_funds_EUR___', 'shap_value': 0.3300335109233856, 'feature_value': -1.029374149889873}, {'feature': 'Of_which_provisions_EUR_Last_avail__yr', 'shap_value': 0.2986792027950287, 'feature_value': 256582.39}, {'feature': 'Capital_EUR_Last_avail__yr', 'shap_value': 0.21577410399913788, 'feature_value': 74582.0}]}, 'SUPERJAM LIMITED': {'predicted_proba': 0.3351908326148987, 'top_features': [{'feature': 'Capital_EUR___', 'shap_value': -0.5471243262290955, 'feature_value': 0.03408455136207065}, {'feature': 'Current_liabilities_EUR_Last_avail__yr', 'shap_value': 0.5297419428825378, 'feature_value': 0.0}, {'feature': 'Debtors_EUR___', 'shap_value': -0.423419326543808, 'feature_value': nan}, {'feature': 'Non_current_assets_EUR___', 'shap_value': -0.3941977918148041, 'feature_value': nan}, {'feature': 'P_L_before_tax_EUR___', 'shap_value': -0.38228633999824524, 'feature_value': nan}]}, 'MERIDIAN MEDICAL OY': {'predicted_proba': 0.6415572762489319, 'top_features': [{'feature': 'Of_which_cash_and_cash_equivalent_EUR_Last_avail__yr', 'shap_value': 0.44489628076553345, 'feature_value': 24000.0}, {'feature': 'Total_assets_EUR___', 'shap_value': -0.4371316432952881, 'feature_value': 0.5176470588235295}, {'feature': 'Other_shareholders_funds_EUR_Last_avail__yr', 'shap_value': 0.3901374340057373, 'feature_value': -873000.0}, {'feature': 'Debtors_EUR___', 'shap_value': -0.37579774856567383, 'feature_value': 1.428571428571429}, {'feature': 'Other_current_liabilities_EUR___', 'shap_value': 0.29927679896354675, 'feature_value': 2.691275167785235}]}, 'CAMORKA OU': {'predicted_proba': 0.9950971007347107, 'top_features': [{'feature': 'NACE_na', 'shap_value': 1.2568588256835938, 'feature_value': True}, {'feature': 'Capital_EUR___', 'shap_value': 0.8383700847625732, 'feature_value': 0.3120666666666667}, {'feature': 'Other_current_liabilities_EUR_Last_avail__yr', 'shap_value': 0.674740731716156, 'feature_value': 7154.0}, {'feature': 'Current_liabilities_EUR_Last_avail__yr', 'shap_value': 0.5289146304130554, 'feature_value': 8704.0}, {'feature': 'Of_which_cash_and_cash_equivalent_EUR_Last_avail__yr', 'shap_value': 0.47329217195510864, 'feature_value': 589.0}]}, 'TWENTY SOMETHING LONDON LIMITED': {'predicted_proba': 0.977331817150116, 'top_features': [{'feature': 'Capital_EUR___', 'shap_value': 1.9252042770385742, 'feature_value': 1.247325662592078}, {'feature': 'Current_liabilities_EUR_Last_avail__yr', 'shap_value': 0.39901602268218994, 'feature_value': 14705.1648695358}, {'feature': 'Non_current_assets_EUR___', 'shap_value': -0.3614542782306671, 'feature_value': 19.18900307685419}, {'feature': 'Capital_EUR_Last_avail__yr', 'shap_value': 0.3149449825286865, 'feature_value': 577.950017014693}, {'feature': 'Total_assets_EUR_Last_avail__yr', 'shap_value': 0.273432195186615, 'feature_value': 42860.5561913807}]}, '3DIVI COMPANY': {'predicted_proba': 0.004412155132740736, 'top_features': [{'feature': 'Number_of_employees___', 'shap_value': -0.8331128358840942, 'feature_value': 0.2916666666666667}, {'feature': 'Number_of_employees_Last_avail__yr', 'shap_value': -0.8201520442962646, 'feature_value': 62.0}, {'feature': 'P_L_before_tax_EUR___', 'shap_value': -0.4257311522960663, 'feature_value': -1.45062858576576}, {'feature': 'P_L_before_tax_EUR_Last_avail__yr', 'shap_value': -0.3233715295791626, 'feature_value': 46677.4739891243}, {'feature': 'Debtors_EUR_Last_avail__yr', 'shap_value': -0.298159658908844, 'feature_value': 443385.551671012}]}, 'TRENDMINER': {'predicted_proba': 0.3810432553291321, 'top_features': [{'feature': 'Number_of_employees_Last_avail__yr', 'shap_value': -0.49547329545021057, 'feature_value': 46.0}, {'feature': 'Number_of_employees___', 'shap_value': -0.37962186336517334, 'feature_value': -0.1481481481481481}, {'feature': 'Tangible_fixed_assets_EUR_Last_avail__yr', 'shap_value': 0.36258479952812195, 'feature_value': 293829.0}, {'feature': 'Of_which_cash_and_cash_equivalent_EUR_Last_avail__yr', 'shap_value': 0.3137556314468384, 'feature_value': 64501.0}, {'feature': 'P_L_for_period___Net_income__EUR_Last_avail__yr', 'shap_value': 0.29928430914878845, 'feature_value': -3866211.0}]}, 'MYDECO LTD': {'predicted_proba': 0.8380123376846313, 'top_features': [{'feature': 'Capital_EUR___', 'shap_value': -1.3996464014053345, 'feature_value': 0.02899392018300454}, {'feature': 'Non_current_assets_EUR___', 'shap_value': 0.864165186882019, 'feature_value': -1.0}, {'feature': 'Other_current_liabilities_EUR_Last_avail__yr', 'shap_value': 0.8014604449272156, 'feature_value': 8045.66406001893}, {'feature': 'Number_of_employees_Last_avail__yr', 'shap_value': -0.7754729986190796, 'feature_value': 79.0}, {'feature': 'Current_liabilities_EUR_Last_avail__yr', 'shap_value': 0.40237075090408325, 'feature_value': 18868.0362751906}]}, 'RAKUTEN SYMPHONY DEUTSCHLAND GMBH': {'predicted_proba': 0.08983919769525528, 'top_features': [{'feature': 'Of_which_cash_and_cash_equivalent_EUR_Last_avail__yr', 'shap_value': -0.7797002792358398, 'feature_value': 15312401.59}, {'feature': 'Tangible_fixed_assets_EUR_Last_avail__yr', 'shap_value': 0.7096289992332458, 'feature_value': 2691891.04}, {'feature': 'Number_of_employees_Last_avail__yr', 'shap_value': -0.5246208906173706, 'feature_value': 81.0}, {'feature': 'Other_current_assets_EUR___', 'shap_value': 0.40164414048194885, 'feature_value': 2.646124548783112}, {'feature': 'Non_current_liabilities_EUR_Last_avail__yr', 'shap_value': -0.3485584259033203, 'feature_value': 23526667.99}]}, 'APPS4PRO': {'predicted_proba': 0.44814348220825195, 'top_features': [{'feature': 'Consolidation_code_NF', 'shap_value': -0.3976574242115021, 'feature_value': True}, {'feature': 'Capital_EUR___', 'shap_value': -0.3858581483364105, 'feature_value': 0.0}, {'feature': 'P_L_for_period___Net_income__EUR_Last_avail__yr', 'shap_value': -0.15882986783981323, 'feature_value': -26484.689202563102}]}, 'CLOUD CYCLE LTD.': {'predicted_proba': 0.883652925491333, 'top_features': [{'feature': 'Capital_EUR___', 'shap_value': 1.2413334846496582, 'feature_value': 0.2657814782995033}, {'feature': 'Tangible_fixed_assets_EUR___', 'shap_value': 0.40239131450653076, 'feature_value': 3.151584997874089}, {'feature': 'Tangible_fixed_assets_EUR_Last_avail__yr', 'shap_value': 0.3664499819278717, 'feature_value': 434954.311847023}, {'feature': 'Non_current_assets_EUR___', 'shap_value': -0.328369677066803, 'feature_value': 3.151584997874089}, {'feature': 'Other_shareholders_funds_EUR_Last_avail__yr', 'shap_value': -0.2732601463794708, 'feature_value': 647937.489903787}]}, 'SMARKETS LIMITED': {'predicted_proba': 0.0029373865108937025, 'top_features': [{'feature': 'Capital_EUR___', 'shap_value': -1.3533601760864258, 'feature_value': 0.01863731197532364}, {'feature': 'Of_which_cash_and_cash_equivalent_EUR_Last_avail__yr', 'shap_value': -0.7661880254745483, 'feature_value': 34673955.8543922}, {'feature': 'Number_of_employees_Last_avail__yr', 'shap_value': -0.6864360570907593, 'feature_value': 91.0}, {'feature': 'Intangible_assets_EUR___', 'shap_value': -0.49185943603515625, 'feature_value': 413.3816585115602}, {'feature': 'Operating_revenue__Turnover__EUR_Last_avail__yr', 'shap_value': -0.46820563077926636, 'feature_value': 24199735.7844332}]}, 'CLEENG B.V.': {'predicted_proba': 0.19686298072338104, 'top_features': [{'feature': 'Other_shareholders_funds_EUR___', 'shap_value': 0.46751415729522705, 'feature_value': 0.5457599889925383}, {'feature': 'Solvency_ratio__Asset_based____', 'shap_value': -0.3707336187362671, 'feature_value': 0.1029472810294729}, {'feature': 'Current_liabilities_EUR_Last_avail__yr', 'shap_value': -0.3464410901069641, 'feature_value': 12602094.0}, {'feature': 'Current_assets_EUR_Last_avail__yr', 'shap_value': -0.25741884112358093, 'feature_value': 13141064.0}]}, 'WEBEVENTS LIMITED': {'predicted_proba': 0.0031323647126555443, 'top_features': [{'feature': 'Capital_EUR___', 'shap_value': -1.791866421699524, 'feature_value': 0.01863731197532309}, {'feature': 'Number_of_employees_Last_avail__yr', 'shap_value': -0.6080294251441956, 'feature_value': 232.0}, {'feature': 'Of_which_cash_and_cash_equivalent_EUR_Last_avail__yr', 'shap_value': -0.5457801818847656, 'feature_value': 6432286.77491651}, {'feature': 'Operating_revenue__Turnover__EUR_Last_avail__yr', 'shap_value': -0.5105428099632263, 'feature_value': 24185905.3882141}, {'feature': 'Other_current_assets_EUR_Last_avail__yr', 'shap_value': -0.3432309329509735, 'feature_value': 29887486.2295529}]}, 'THINGARAGE S.R.L. IN LIQUIDAZIONE': {'predicted_proba': 0.9357014298439026, 'top_features': [{'feature': 'Of_which_cash_and_cash_equivalent_EUR_Last_avail__yr', 'shap_value': 0.41627737879753113, 'feature_value': 1127.0}, {'feature': 'Current_liabilities_EUR___', 'shap_value': 0.3421587646007538, 'feature_value': -0.7161488300728807}, {'feature': 'Current_assets_EUR_Last_avail__yr', 'shap_value': 0.3234782814979553, 'feature_value': 2745.0}, {'feature': 'Current_liabilities_EUR_Last_avail__yr', 'shap_value': 0.30564019083976746, 'feature_value': 740.0}, {'feature': 'Debtors_EUR_Last_avail__yr', 'shap_value': 0.24815858900547028, 'feature_value': 0.0}]}, 'DYNMARK INTERNATIONAL LIMITED': {'predicted_proba': 0.5841038823127747, 'top_features': [{'feature': 'Consolidation_code_NF', 'shap_value': -0.3745284676551819, 'feature_value': True}, {'feature': 'NACE_na', 'shap_value': 0.3613632321357727, 'feature_value': True}, {'feature': 'Capital_EUR___', 'shap_value': -0.35990434885025024, 'feature_value': 0.0}, {'feature': 'Operating_revenue__Turnover__EUR_Last_avail__yr', 'shap_value': 0.1762586236000061, 'feature_value': 106690.3966795545}]}, 'IMPOSSIBLE SOFTWARE GMBH': {'predicted_proba': 0.4279686212539673, 'top_features': [{'feature': 'Capital_EUR___', 'shap_value': -0.33766475319862366, 'feature_value': 0.0}, {'feature': 'Current_assets_EUR___', 'shap_value': 0.13789063692092896, 'feature_value': -0.014479097142360734}, {'feature': 'Current_assets_EUR_Last_avail__yr', 'shap_value': 0.13354229927062988, 'feature_value': 362620.634501137}]}, 'SMART HYDRO POWER GMBH': {'predicted_proba': 0.3675731420516968, 'top_features': [{'feature': 'Of_which_cash_and_cash_equivalent_EUR_Last_avail__yr', 'shap_value': 0.4814416766166687, 'feature_value': 543.33}, {'feature': 'Number_of_employees_Last_avail__yr', 'shap_value': -0.3168831765651703, 'feature_value': 1.0}, {'feature': 'Other_current_liabilities_EUR___', 'shap_value': 0.2987452447414398, 'feature_value': -0.9828483209769483}, {'feature': 'Debtors_EUR___', 'shap_value': -0.2866959571838379, 'feature_value': 2.100304680090475}, {'feature': 'Solvency_ratio__Asset_based____', 'shap_value': -0.271052747964859, 'feature_value': 0.3471349585322944}]}, 'WHIPCAR LTD': {'predicted_proba': 0.6580085754394531, 'top_features': [{'feature': 'Capital_EUR___', 'shap_value': 1.253055214881897, 'feature_value': 2.206175882977049}, {'feature': 'Of_which_cash_and_cash_equivalent_EUR_Last_avail__yr', 'shap_value': -0.37439313530921936, 'feature_value': 1441306.39312453}, {'feature': 'Debtors_EUR___', 'shap_value': -0.3159739375114441, 'feature_value': 4.682047414143084}, {'feature': 'Net_current_assets_EUR_Last_avail__yr', 'shap_value': -0.25301042199134827, 'feature_value': 1644760.71616406}, {'feature': 'Capital_EUR_Last_avail__yr', 'shap_value': -0.24539484083652496, 'feature_value': 3566206.51021394}]}, 'USE IT BETTER SP. Z O.O.': {'predicted_proba': 0.39456039667129517, 'top_features': [{'feature': 'Capital_EUR___', 'shap_value': 1.0329476594924927, 'feature_value': 0.07975314604007841}, {'feature': 'Debtors_EUR___', 'shap_value': -0.444293349981308, 'feature_value': 1.159506292080153}, {'feature': 'P_L_before_tax_EUR_Last_avail__yr', 'shap_value': -0.3620668947696686, 'feature_value': 197784.048639094}, {'feature': 'Capital_EUR_Last_avail__yr', 'shap_value': 0.3161241412162781, 'feature_value': 6439.48065336584}]}, 'CHRISTOPHER O LTD': {'predicted_proba': 0.03244490921497345, 'top_features': [{'feature': 'Number_of_employ

In [4]:
# Read the Excel output file
output_df = pd.read_excel('../data/output.xlsx')
output_df = output_df[output_df['Standardized country'] != 'Russia']
output_df.rename(columns={'Standardized country': 'country', 'Company name Latin alphabet': 'company_name'}, inplace=True)

print("Sample of the output DataFrame:")
display(HTML(output_df.head().style.to_html()))

Sample of the output DataFrame:

In [5]:
# Create a DataFrame with company_name and predicted_proba
data = [{'company_name': company, 'predicted_proba': prob['predicted_proba']} for company, prob in firm_explanations.items()]
df1 = pd.DataFrame(data)

print("Predictions DataFrame:")
display(HTML(df1.head(10).style.to_html()))

Predictions DataFrame:

In [6]:
# Join the first two datasets
df1 = pd.merge(df1, output_df, on='company_name', how='inner')
print("Merged DataFrame Sample:")
display(HTML(df1.head().style.to_html()))

Merged DataFrame Sample:

In [7]:
# Create a list to store all feature data
feature_data = []

# Iterate through each company and their features
for company_name, data in firm_explanations.items():
    # Get features and their values
    features = data['top_features']
    
    # Sort features by absolute SHAP value to assign ranks
    sorted_features = sorted(features, key=lambda x: abs(x['shap_value']), reverse=True)
    
    # Add each feature with its rank
    for rank, feature in enumerate(sorted_features, 1):
        feature_data.append({
            'company_name': company_name,
            'feature': feature['feature'],
            'feature_value': feature['feature_value'],
            'shap_value': feature['shap_value'],
            'rank': rank
        })

# Create DataFrame
df2 = pd.DataFrame(feature_data)

print("Sample of the feature DataFrame:")
display(HTML(df2.head(10).to_html()))

Sample of the feature DataFrame:

In [ ]:
print(df2['feature'].unique())

['Consolidation_code_NF' 'Capital_EUR___'
 'Current_assets_EUR_Last_avail__yr' 'Current_assets_EUR___'
 'Tangible_fixed_assets_EUR_Last_avail__yr'
 'Of_which_cash_and_cash_equivalent_EUR_Last_avail__yr'
 'Number_of_employees_Last_avail__yr' 'Long_term_debt_EUR_Last_avail__yr'
 'Intangible_assets_EUR___' 'Non_current_assets_EUR___'
 'Debtors_EUR_Last_avail__yr' 'P_L_before_tax_EUR___'
 'P_L_for_period___Net_income__EUR_Last_avail__yr'
 'Capital_EUR_Last_avail__yr' 'Current_liabilities_EUR_Last_avail__yr'
 'Total_shareholders__funds_and_liabilities_EUR___'
 'Non_current_liabilities_EUR___' 'Solvency_ratio__Asset_based____'
 'Current_liabilities_EUR___' 'Other_current_liabilities_EUR___'
 'Quoted_Yes' 'Debtors_EUR___' 'Consolidation_code_LF'
 'Other_shareholders_funds_EUR___' 'Tangible_fixed_assets_EUR___'
 'Total_assets_EUR_Last_avail__yr' 'Shareholders_funds_EUR___'
 'Of_which_provisions_EUR_Last_avail__yr' 'Total_assets_EUR___'
 'Other_shareholders_funds_EUR_Last_avail__yr' 'NACE_na'
 'Other_current_liabilities_EUR_Last_avail__yr' 'Number_of_employees___'
 'P_L_before_tax_EUR_Last_avail__yr' 'Other_current_assets_EUR___'
 'Non_current_liabilities_EUR_Last_avail__yr'
 'Operating_revenue__Turnover__EUR_Last_avail__yr'
 'Other_current_assets_EUR_Last_avail__yr'
 'Net_current_assets_EUR_Last_avail__yr'
 'Of_which_cash_and_cash_equivalent_EUR___' 'Creditors_EUR_Last_avail__yr'
 'Working_capital_EUR_Last_avail__yr' 'NACE_63'
 'Intangible_assets_EUR_Last_avail__yr'
 'Other_non_current_assets_EUR_Last_avail__yr'
 'Non_current_assets_EUR_Last_avail__yr' 'Woco_Yes'
 'Shareholders_funds_EUR_Last_avail__yr' 'NACE_61'
 'Net_current_assets_EUR___' 'Creditors_EUR___'
 'Current_ratio_Last_avail__yr' 'Stock_EUR_Last_avail__yr'
 'Solvency_ratio__Asset_based__Last_avail__yr'
 'Depreciation___Amortization_EUR_Last_avail__yr' 'Current_ratio___'
 'P_L_for_period___Net_income__EUR___' 'Working_capital_EUR___' 'NACE_47'
 'Loans___short_term_debt_EUR_Last_avail__yr' 'Consolidation_code_U1'
 'NACE_28' 'Total_shareholders__funds_and_liabilities_EUR_Last_avail__yr']

In [9]:
# Function to clean up feature names
def clean_feature_name(feature_name):
    # Add parentheses for "Last avail yr"
    feature_name = feature_name.replace('Last_avail__yr', '(Last avail. yr)')
    # Remove underscores and "EUR"
    feature_name = feature_name.replace('_', ' ').replace('EUR', '').strip()
    # Clean up P/L
    feature_name = feature_name.replace('P L', 'P/L')
    return feature_name

# Apply the function to the feature column
df2['feature'] = df2['feature'].apply(clean_feature_name)

print("Cleaned feature names:")
display(HTML(df2.head(10).to_html()))

Cleaned feature names:

In [10]:
df2.to_csv('../data/shapley_features.tsv', sep='\t', index=False)

In [11]:
df1.to_csv('../data/output_with_predictions.tsv', sep='\t', index=False)

In [37]:
print(df1.columns.tolist())

['company_name', 'predicted_proba', 'Quoted', 'Branch', 'Woco', 'NACE Rev. 2, core code (4 digits)', 'Consolidation code', 'country', 'Operating revenue (Turnover)\nEUR Last avail. yr', 'P/L before tax\nEUR Last avail. yr', 'P/L for period [=Net income]\nEUR Last avail. yr', 'Total assets\nEUR Last avail. yr', 'Shareholders funds\nEUR Last avail. yr', 'Current ratio\nLast avail. yr', 'Solvency ratio (Asset based)\nLast avail. yr', 'Number of employees\nLast avail. yr', 'Non-current assets\nEUR Last avail. yr', 'Intangible assets\nEUR Last avail. yr', 'Tangible fixed assets\nEUR Last avail. yr', 'Other non-current assets\nEUR Last avail. yr', 'Current assets\nEUR Last avail. yr', 'Stock\nEUR Last avail. yr', 'Debtors\nEUR Last avail. yr', 'Other current assets\nEUR Last avail. yr', 'Of which cash and cash equivalent\nEUR Last avail. yr', 'Capital\nEUR Last avail. yr', 'Other shareholders funds\nEUR Last avail. yr', 'Non-current liabilities\nEUR Last avail. yr', 'Long term debt\nEUR Last avail. yr', 'Other non-current liabilities\nEUR Last avail. yr', 'Of which provisions\nEUR Last avail. yr', 'Current liabilities\nEUR Last avail. yr', 'Loans & short-term debt\nEUR Last avail. yr', 'Creditors\nEUR Last avail. yr', 'Other current liabilities\nEUR Last avail. yr', "Total shareholders' funds and liabilities\nEUR Last avail. yr", 'Working capital\nEUR Last avail. yr', 'Net current assets\nEUR Last avail. yr', 'Depreciation & Amortization\nEUR Last avail. yr', 'Status Updated', 'Shareholders funds\nEUR Δ%', 'Other current assets\nEUR Δ%', 'Debtors\nEUR Δ%', 'Non-current liabilities\nEUR Δ%', 'P/L before tax\nEUR Δ%', 'Total assets\nEUR Δ%', 'Creditors\nEUR Δ%', 'Intangible assets\nEUR Δ%', 'P/L for period [=Net income]\nEUR Δ%', 'Solvency ratio (Asset based) Δ%', 'Of which cash and cash equivalent\nEUR Δ%', 'Other current liabilities\nEUR Δ%', 'Non-current assets\nEUR Δ%', 'Current assets\nEUR Δ%', 'Tangible fixed assets\nEUR Δ%', 'Current ratio Δ%', 'Other shareholders funds\nEUR Δ%', 'Capital\nEUR Δ%', 'Current liabilities\nEUR Δ%', 'Number of employees Δ%', 'Working capital\nEUR Δ%', 'Net current assets\nEUR Δ%', "Total shareholders' funds and liabilities\nEUR Δ%"]

In [12]:
min_shap_value = df2['shap_value'].min()
max_shap_value = df2['shap_value'].max()

print(f"Minimum SHAP value: {min_shap_value}")
print(f"Maximum SHAP value: {max_shap_value}")

Minimum SHAP value: -3.2986814975738525
Maximum SHAP value: 1.949305534362793

In [15]:
adludio_row = df1[df1['company_name'].str.startswith('ADLUDIO')]
display(HTML(adludio_row.to_html()))